Make instructions for Docker run more readable
root-project/web pull request #906
Opened 2023-10-19 16:50 UTC by JRS296

- Removed misleading '.' for docker run command
- Added few more steps for Docker pulls (based out of DockerHub documentation)
- Overall, made Docker section more readable.

Image to explain need for reformatted test (within Markdown code block):
![PR](https://github.com/root-project/web/assets/70965472/6dc59fda-9677-4ae4-97b3-752da2658d69)

- I personally had trouble with the given text as the fullstop after the command brought around the assumption that the current directory was to be specified during the docker dun command? Therefore, edited it out to make it more readable + Added extra run commands (based from the Docker Hub page).

2023-10-19 16:53 UTC, JRS296 commented
@couet and @Axel-Naumann, can I have this PR reviewed? And if it is acceptable, kindly grant approval for the Jekyll build check. Thanks.

2023-10-25 05:37 UTC, JRS296 commented
@couet and @Axel-Naumann, can I get this PR reviewed? Thanks.

2023-10-25 07:49 UTC, couet approved these changes
LGTM

2023-10-25 11:01 UTC, Axel-Naumann requested changes
Please reference docker doc instead of duplicating non-ROOT related details here. Thanks for fixing the training `.`!

2023-10-25 12:42 UTC, JRS296 commented
I've made the changes, removed all the non-trivial info, and limited change to just removal of trailing '.'
@Axel-Naumann it should be ready now

2023-10-25 13:12 UTC, Axel-Naumann requested changes

2023-10-25 13:12 UTC, Axel-Naumann commented on install/index.md
> +For more instructions on running root's docker image, visit [ROOT's official DockerHub](https://hub.docker.com/r/rootproject){:target="\_blank"}.
That link sends me to https://hub.docker.com/u/rootproject

And that doesn't have any instructions. Maybe we can share generic Docker instructions? Or use https://hub.docker.com/r/rootproject/root as link?

2023-10-25 19:24 UTC, JRS296 commented on install/index.md
> +docker run --rm -it rootproject/root:latest
Ahh yes of course. Would be quite the shock for a first-timer to have their container removed because of it XD. We can have it without the --rm 👍

2023-10-25 20:14 UTC, Axel-Naumann approved these changes
Thanks a lot and apologies for the salami review!

2023-10-27 08:30 UTC, merged